<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tm_cognito"
 *
 * Auto generated by Extension Builder 2019-11-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'saml authentication',
    'description' => 'saml authentication using simplesamphp',
    'category' => 'plugin',
    'author' => 'Simon Ouellet',
    'author_email' => 'simon.ouellet@toumoro.com',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' =>
    array(
        'psr-4' =>
            array(
            'Toumoro\\TmSaml\\' => 'Classes'
        )
    )
];
